### ISSUE TITLE
Front end click on locator not working on Safari

### ISSUE THREAD

**Issue by robertpassaro** [gsarig/ootb-openstreetmap#1] opened 2021-02-03 01:43 UTC
Excellent plugin!! I love this! I am finding one weird issue when I happened to be in Safari -- if you place a pin on the map, and click on it on the front end the pop-up does not appear. It seems to be working fine on Firefox and Chrome. Can you reproduce this?

**Comment by gsarig** [comment] 2021-03-14 16:17
Hi Robert, thanks for your comment and sorry for the delayed response. 

I don't have an actual map to properly try it, but I am testing it on an emulator, using lambdatest.com. 
I can confirm that the popup doesn't open when clicked. It does open if I click and hold for a while (1-2 seconds) and then release it. This seems to be a leaflet issue, as I notice the same behavior on their official example: https://leafletjs.com/

**Comment by 0dysseo** [comment] 2022-11-05 10:03
Hello Giorgios, greetings from France.
Any update about this issue?
I've installed your plug-in and actually one of my customers is experiencing the same problem.
Pls let me know. Thanks in advance

**Comment by gsarig** [comment] 2022-11-13 22:58
Hi @0dysseo This seems to be a `Leaflet` bug which, based on my tests, seems to have been resolved in the newer versions. I'm working on a big refactoring of the plugin, which will update `Leaflet` as well, and it should fix the issue. If you are interested in more details, you can [check it out](https://github.com/gsarig/ootb-openstreetmap/pull/3). 


As I am working on it on my free time (usually the weekends), I expect to have it fully tested and released (hopefully) by the end of the month. 

Unfortunately, Leaflet 4* had been a big upgrade, and parts of the plugin's functionality had to be rewritten to support it, that's why it took me so long. 

In the meantime, if you want something faster, I've prepared a zip for you, and you can use the attached version of the plugin:

**[ootb-openstreetmap.zip](https://github.com/gsarig/ootb-openstreetmap/files/9998402/ootb-openstreetmap.zip)**

Just upload the plugin from the WordPress dashboard, and when prompted, allow it to override the existing one. Of course, I would suggest to test if first on a staging environment, as I have only tested it on very specific conditions (WordPpress 6.1, and PHP 7.4 and 8.0). 

If you decide to test it, please let me know for any issues or bugs. On my tests it worked fine, but as I said, I only used a very specific environment so far.

**Comment by gsarig** [comment] 2022-11-28 11:47
This should be fixed on v. 2.0.0

**Closed by gsarig** 2022-11-28 11:47 UTC
